---

src_parent_dir: 'spec/integration/src'

report_dir:
  :full: 'spec/integration/datasets/ht_text/history'
  :pd: 'spec/integration/datasets/ht_text_pd/history'
  :pd_open: 'spec/integration/datasets/ht_text_pd_open_access/history'
  :pd_world: 'spec/integration/datasets/ht_text_pd_world/history'
  :pd_world_open: 'spec/integration/datasets/ht_text_pd_world_open_access/history'


dest_parent_dir:
  :full: 'spec/integration/datasets/ht_text'
  :pd: 'spec/integration/datasets/ht_text_pd'
  :pd_open: 'spec/integration/datasets/ht_text_pd_open_access'
  :pd_world: 'spec/integration/datasets/ht_text_pd_world'
  :pd_world_open: 'spec/integration/datasets/ht_text_pd_world_open_access'

feed_db:
  adapter: sqlite
  database: spec/integration/feed.db

rights_db:
  adapter: sqlite
  database: spec/integration/rights.db
