---

# This is the config.yml to use when using the
# Datasets::Hathitrust::Configuration.

src_parent_dir:  full/src/path

dest_parent_dir:
  full: full/dest/path
  pd: pd/dest/path

report_dir:
  full: full/dest/path/history
  pd: pd/dest/path/history

db:
  adapter: sqlite
  database: spec/integration/demo.db
